[project]
name = "napari-workflow-tasks"
dynamic = ["version"]
description = "A plugin to interact with OME-Zarr tasks"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
  {name = "Daniel Krentzel"},
  {email = "dkrentzel@pm.me"},
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Framework :: napari",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Image Processing",
]
requires-python = ">=3.8, <3.12"
dependencies = [
    "numpy",
    "magicgui",
    "qtpy",
    "scikit-image",
    "ngio",
    "napari",
]

[project.optional-dependencies]
testing = [
    "tox",
    "pytest",
    "pytest-cov",
    "pytest-qt",
    "pooch",
]

[project.entry-points."napari.manifest"]
napari-workflow-tasks = "napari_workflow_tasks:napari.yaml"

[project.urls]
"Bug Tracker" = "https://github.com/krentzd/napari-workflow-tasks/issues"
"Documentation" = "https://github.com/krentzd/napari-workflow-tasks#README.md"
"Source Code" = "https://github.com/krentzd/napari-workflow-tasks"
"User Support" = "https://github.com/krentzd/napari-workflow-tasks/issues"

[build-system]
requires = ["setuptools>=42.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.yaml"]

[tool.setuptools.dynamic]
version = {attr = "napari_workflow_tasks.__init__.__version__"}

[tool.black]
line-length = 79
target-version = ['py38', 'py39', 'py310']

[tool.ruff]
line-length = 79
lint.select = [
    "E", "F", "W",
    "UP",
    "I",
    "BLE",
    "B",
    "A",
    "C4",
    "ISC",
    "G",
    "PIE",
    "SIM",
]
lint.ignore = [
    "E501",
    "UP006", "UP007",
    "SIM117",
]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".mypy_cache",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "*vendored*",
    "*_vendor*",
]
target-version = "py38"
fix = true

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64", "win-64", "linux-64"]

[tool.pixi.pypi-dependencies]
napari-workflow-tasks = { path = ".", editable = true }
numpy = "*"
magicgui = "*"
qtpy = "*"
scikit-image = "*"
ngio = "*"
napari = "*"
napari-ome-zarr = "*"

[tool.pixi.dependencies]
pyqt = ">=5.15,<6"

[tool.pixi.environments]
default = { solve-group = "default" }
testing = { features = ["testing"], solve-group = "default" }